<?php
if ( !defined( 'ABSPATH' ) ) {  die(); }
?>

<h2>Dojo Plugin Dummy Page</h2>
<p>This is a placeholder page used to apply theme settings to dynamic pages generated by the plugin.</p>
<p>If your theme has custom page settings you can apply them to this page to affect all dojo pages.</p>
